# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36bb575fe9f093cff17ef0db3f80581165f63dc82d6b9f1c5142fa08202aa89f5c968878da3df4f2e138eec082b6e7915c504d1e5e8f85f59d41eae0b645dcda

test:
  secret_key_base: ca571cb7353a7dd8956afdc12404c2b88cd7775d782f3f7354d64e1f7093973c667a1b539a8cd5473f1e55a361fedab10d99a001394865c151bff05278a2da61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
