
# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml

:verbose: false
:concurrency: 5
:logile: log/sidekiq_development.log
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - default